---
- name: Collect Commands
  hosts: aristainfra
  connection: local
  gather_facts: false
  collections:
    - arista.avd
  tasks:
    - name: Collect commands
      ansible.builtin.import_role:
        name: eos_snapshot
    - name: Assemble single report
      shell:
        cmd: 'cat snapshots/*/*.md > All-Device-Report.md'