---
- name: Collect Commands
  hosts: otpjefflab
  connection: local
  gather_facts: false
  collections:
    - arista.avd
  tasks:
    - name: Collect commands
      ansible.builtin.import_role:
        name: eos_snapshot
    - name: Assemble report
      ansible.builtin.assemble:
        src: ./snapshots/.
        dest: ./snapshots/myreport.md